### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by PeteCoward** [pykafe/timorGIS#205]
Try tio install django 3, and see if the site still works
`pip install Django==3`
and run `./manage.py check` to see if we have any problems, and the `./manage.py runserver` to see if the site still works.

If everything is good, then update the requirements.txt file to use the Django 3 LTS

**Comment by eraulo** [comment]
I get this error in the console:


WARNINGS:
map.Aldeia: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
map.District: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
map.IstoriaViazen: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
map.PhotoTimor: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
map.Subdistrict: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
map.Suco: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the MapConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

**Comment by PeteCoward** [comment]
to fix the above set `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'` in setting.py

**Comment by joanico** [comment]
Error in browser

TypeError at /en/
'IFDRational' object does not support indexing
