### ISSUE TITLE
Improve interface for upload image

### ISSUE THREAD

**Issue by eraulo** [pykafe/timorGIS#54]
![Screenshot from 2020-04-18 15-13-17](https://user-images.githubusercontent.com/12780219/79629846-a0689d00-8187-11ea-9a6f-3133387455cb.png)

**Comment by marobo** [comment]
@eraulo favor labele kontinua lai issue nee tamba @MarioAP ohin komplein hela ho add istoria viajen, tamba ita haree hanesan ita separa/repete formulariu fali.

**Comment by eraulo** [comment]
@marobo susar uituan ita atu tau hamutuk upload images iha istoriaviazen form, hau koko tiha ona maibe so upload images ida deit barak nia la simu ida  no ida lori mak ita halo ida. Agora ita halai ida ne'e ba futuru mak ita bele hadia ida ne'e.
